GEMINI_API_KEY = "AIzaSyDJ69j4GVcxE3y4sKXDlgS55oC0VInmXes"

[auth]
redirect_uri = "https://synapsemd.ici-labs.com/oauth2callback"
cookie_secret = "UfvZCl2YxSAoz5D7N3TX9EWZ4pYdxZXikf9GYv9zld8m0IDzarplrPyqSo6_q1yeAVJ7XrRauo7wkKUXrWHu_A"
client_id = "322482981441-fdm2oc5iv1ng5ll06ctd4g1u2tuku95l.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
scopes = ["openid", "email", "profile"]


